### ISSUE TITLE
Error when calling pixel2poly function

### ISSUE THREAD

**Issue by jordinagili** [TomasBeuzen/python-for-geospatial-analysis#1]
Hi Tomas,

After installing the "utils" module I am getting this error when I try to import the pixel2poly function:

> cannot import name 'pixel2poly' from 'utils'

Is still available?

Thank you,

Jordina

**Comment by TomasBeuzen** [comment]
Hello @jordinagili - yes [the function still exists](https://github.com/TomasBeuzen/python-for-geospatial-analysis/blob/main/chapters/scripts/utils.py). Is there more information to the error? Can you not import because you don't have the dependencies installed (i.e., `numpy`, `pandas`, `shapely`). Or can it not be found?

**Comment by jordinagili** [comment]
I finally have called it directly from the notebook terminal and it worked perfectly. Thanks!
I also wanted to ask if there is any way to make the mesh of the map resulting from the interpolation smaller? To have more detail.

Thank you very much,

Jordina

**Comment by TomasBeuzen** [comment]
Yep - the last argument to `pixel2poly(x, y, z, resolution)` is `resolution`. Which, from memory, is the mesh cell size in meters. So reducing this number would result in a finer mesh (but computational demand will increase).

**Comment by jordinagili** [comment]
I see. Thanks!

**Comment by jordinagili** [comment]
Hi again Tomas,

Would it be possible to extract the modeled PM2.5 data to csv?

Thanks,

Jordina
